name: train_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  ar_flutter_plugin_flutterflow: ^0.7.39

  geoflutterfire: "^3.0.1"
  path_provider: ^2.0.3
  flutter_archive: ^6.0.3
  permission_handler: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - Images/triangle.png
    - Models/Chicken_01/
